// Content for the Odyssey AI-comparison discussion. Everything here is editorial data; components only render it.
// Rule: nothing in this file is a statistic unless it carries a `src`. Conceptual ratings are labelled as such.

export type LabelKind = "fact" | "supported" | "ai" | "inference" | "uncertain";
export const LABELS: Record<LabelKind, { name: string; def: string }> = {
  fact: { name: "Fact", def: "Directly checkable historical or contemporary information." },
  supported: { name: "Supported interpretation", def: "A reading supported by scholarship, criticism or documented cultural use." },
  ai: { name: "AI analysis", def: "Reasoning produced by comparing the three AI responses." },
  inference: { name: "Inference", def: "A conclusion generated by ThinkScope from the available evidence." },
  uncertain: { name: "Uncertain", def: "Evidence is incomplete, disputed or insufficient." },
};

export type BadgeKind = "text" | "interp" | "aiinf" | "unc";
export const BADGES: Record<BadgeKind, string> = { text: "TEXT", interp: "INTERPRETATION", aiinf: "AI INFERENCE", unc: "UNCERTAIN" };

export interface Src { label: string; href: string }

/* ---------- 1. Three AIs ---------- */
export interface AICard { id: string; model: string; emphasis: string; themes: string; insight: string; caution: string; evidence: string }
export const AI_CARDS: AICard[] = [
  { id: "gemini", model: "Gemini", emphasis: "Modern parallels and adaptability.",
    themes: "Homecoming, identity, loyalty, temptation, family, war, leadership, revenge, hospitality, resilience, disguise, fate and choice.",
    insight: "The story can be mapped onto modern experiences such as migration, veteran reintegration, digital identity, online self-presentation and modern forms of distraction.",
    caution: "Many of these connections are modern interpretations rather than direct equivalences with ancient Greek life.",
    evidence: "Analogy-led: moves from textual episodes to modern experiences." },
  { id: "chatgpt", model: "ChatGPT", emphasis: "Adaptable human problems combined with the difference between ancient and modern contexts.",
    themes: "Homecoming, identity, family, resilience, temptation, hospitality, storytelling, fate and choice.",
    insight: "The circumstances are not universal, but the questions can be transferable.",
    caution: "Adaptation and continued cultural attention do not automatically prove that contemporary audiences personally find the poem relevant.",
    evidence: "Context-led: separates ancient circumstances from transferable questions." },
  { id: "claude", model: "Claude", emphasis: "Evidence discipline and cultural renewal.",
    themes: "Homecoming, hospitality, recognition/disguise, mortality, moral ambiguity, revenge, storytelling and retelling.",
    insight: "The Odyssey may be better described as \u201crenewable\u201d rather than simply \u201ctimeless.\u201d",
    caution: "Attention to adaptations or film success does not automatically prove understanding, reading or long-term relevance of the original poem.",
    evidence: "Test-led: asks what independent evidence supports each connection." },
];

/* ---------- 2. Convergence (ThinkScope coding supplied by the editor) ---------- */
export const CONVERGENCE: { theme: string; n: 1 | 2 | 3 }[] = [
  { theme: "Homecoming", n: 3 }, { theme: "Identity & recognition", n: 3 }, { theme: "Family & belonging", n: 3 }, { theme: "War & aftermath", n: 3 },
  { theme: "Hospitality", n: 3 }, { theme: "Storytelling & retelling", n: 3 }, { theme: "Resilience", n: 3 }, { theme: "Temptation", n: 3 },
  { theme: "Fate & choice", n: 3 }, { theme: "Revenge", n: 2 }, { theme: "Mortality", n: 1 }, { theme: "Digital identity", n: 1 },
];
export const CONVERGENCE_LEGEND: Record<1 | 2 | 3, string> = { 3: "explicitly emphasized by all three analyses", 2: "explicitly emphasized by two analyses", 1: "distinctive emphasis in one analysis" };

/* ---------- 3. Divergence ---------- */
export const DIVERGENCE = [
  { id: "gemini", model: "Gemini", title: "The modern mirror", short: "Shows how ancient themes can be interpreted through modern experiences.",
    asks: "What in modern life does this episode resemble?", move: "Maps episodes such as the return to Ithaca or the Sirens onto experiences like reintegration after war or online distraction.", risk: "Analogies can feel convincing without being evidence." },
  { id: "chatgpt", model: "ChatGPT", title: "The transferable question", short: "Focuses on the difference between ancient circumstances and transferable human questions.",
    asks: "Which part is circumstance, and which part is a question that can travel?", move: "Sets aside the ancient institutions and keeps the question underneath, such as what home means after change.", risk: "\u201cTransferable\u201d can become too vague to test." },
  { id: "claude", model: "Claude", title: "The evidence test", short: "Asks whether the modern interpretation has enough independent evidence to justify the connection.",
    asks: "Is there independent evidence for this link, beyond the fact that it sounds plausible?", move: "Checks a connection against the text, against documented modern use, and against the gap between ancient and modern society.", risk: "A strict test may reject readings that readers find meaningful." },
];

/* ---------- 4. Evidence test (reusable) ---------- */
export type Rating = "Strong" | "Moderate" | "Partial" | "Weak" | "Strongly interpretive";
export interface EvidenceStep { rating: Rating; note: string }
export interface EvidenceCase {
  id: string; label: string; textual: Rating; modern: Rating; reason: string;
  anchor: EvidenceStep; uptake: EvidenceStep; resistance: EvidenceStep; sources?: Src[];
}
export const EVIDENCE_STEPS = [
  { n: 1, name: "Textual anchor", q: "Is the idea clearly present in The Odyssey?" },
  { n: 2, name: "Modern uptake", q: "Has the idea independently appeared in modern scholarship, literature, film, theatre, criticism or other cultural use?" },
  { n: 3, name: "Ancient/modern resistance", q: "Does the interpretation survive the major differences between ancient Greek society and modern society?" },
] as const;
export const EVIDENCE_CASES: EvidenceCase[] = [
  { id: "home", label: "Home / homecoming", textual: "Strong", modern: "Moderate",
    reason: "The poem is explicitly structured around Odysseus' return to Ithaca, but modern concepts such as migration, exile, military reintegration and personal transformation are interpretations rather than direct equivalents.",
    anchor: { rating: "Strong", note: "Odysseus is kept from Ithaca (Books 1 and 5), reaches it in Book 13, and the second half of the poem is about reclaiming his household." },
    uptake: { rating: "Moderate", note: "Documented: Jonathan Shay's Odysseus in America (2002) reads the poem alongside veterans' homecoming, and Joyce's Ulysses and the Coen brothers' O Brother, Where Art Thou? are loosely built on it. Links to migration or exile are less documented." },
    resistance: { rating: "Partial", note: "Ancient nostos is a return to household, status and kin in an aristocratic world. It survives as a question about belonging, not as a like-for-like equivalent. (ThinkScope inference.)" },
    sources: [{ label: "Shay, Odysseus in America (Scribner, 2002)", href: "https://en.wikipedia.org/wiki/Jonathan_Shay" }, { label: "Nostos", href: "https://en.wikipedia.org/wiki/Nostos" }] },
  { id: "identity", label: "Identity / disguise", textual: "Strong", modern: "Moderate",
    reason: "Disguise and recognition are central to the plot (the beggar disguise, the scar, the bed). Modern ideas of individual selfhood are a later layer that readers bring to those scenes.",
    anchor: { rating: "Strong", note: "Athena disguises Odysseus as a beggar in Book 13; Eurycleia recognises his scar in Book 19; Penelope's bed test comes in Book 23." },
    uptake: { rating: "Moderate", note: "Documented: Erich Auerbach's essay \u201cOdysseus' Scar\u201d (in Mimesis, 1946) is a well-known critical treatment of recognition in the poem. Modern psychological readings are more varied." },
    resistance: { rating: "Partial", note: "In the poem recognition runs through proofs such as scars and household secrets, within a world of status and kin. Modern identity is more individual and psychological, so the link works as a question, not an equivalence. (ThinkScope inference.)" },
    sources: [{ label: "Auerbach, Mimesis (1946)", href: "https://en.wikipedia.org/wiki/Mimesis:_The_Representation_of_Reality_in_Western_Literature" }] },
  { id: "hospitality", label: "Hospitality (xenia)", textual: "Strong", modern: "Moderate",
    reason: "Guest-friendship is tested again and again in the text. Modern questions about migrants, refugees and strangers are interpretations of that pattern, not the same institution.",
    anchor: { rating: "Strong", note: "Polyphemus violates it (Book 9); the Phaeacians and Eumaeus honour it (Books 6\u201313, 14); the suitors abuse it throughout the household." },
    uptake: { rating: "Moderate", note: "Documented: M. I. Finley's The World of Odysseus (1954) is a classic study of guest-friendship in the poem's world. Readings that connect xenia to modern refugees are interpretations and less documented." },
    resistance: { rating: "Partial", note: "Xenia was reciprocal, tied to gifts, status and the protection of Zeus. Modern obligations to strangers are legal and humanitarian. The question travels; the institution does not. (ThinkScope inference.)" },
    sources: [{ label: "Xenia (Greek)", href: "https://en.wikipedia.org/wiki/Xenia_(Greek)" }] },
  { id: "mortality", label: "Mortality", textual: "Strong", modern: "Moderate",
    reason: "The text sets a finite human life against immortality and the dead. How that speaks to modern readers is a matter of interpretation, and this page does not cite specific scholarship for it.",
    anchor: { rating: "Strong", note: "In Book 5 Odysseus declines Calypso's offer of immortality; in Book 11 he speaks with the dead in the Underworld." },
    uptake: { rating: "Moderate", note: "ThinkScope's conceptual rating. This page does not cite specific modern scholarship for this theme, and it was a distinctive emphasis in one AI analysis." },
    resistance: { rating: "Partial", note: "Ancient ideas of the afterlife and of fame after death differ from modern ones, so the transferable part is the question of what makes a finite life meaningful. (ThinkScope inference.)" } },
  { id: "digital", label: "Digital identity", textual: "Weak", modern: "Strongly interpretive",
    reason: "The poem has no direct equivalent of online identity. The nearest textual hooks are names and disguise; the parallel mostly comes from the modern reader.",
    anchor: { rating: "Weak", note: "No direct textual equivalent. The nearest hooks are disguise and the \u201cNobody\u201d name Odysseus uses with Polyphemus in Book 9." },
    uptake: { rating: "Weak", note: "ThinkScope has not checked independent modern uptake. The parallel appeared in one AI analysis (Gemini)." },
    resistance: { rating: "Weak", note: "It does not survive as an equivalence; at most it works as an analogy. (ThinkScope inference.)" } },
  { id: "addiction", label: "Modern addiction / distraction", textual: "Weak", modern: "Strongly interpretive",
    reason: "Lotus-Eaters, Sirens and Calypso are episodes of temptation and delay. \u201cAddiction\u201d is a modern medical and psychological category the poem does not use; Gemini's own wording was \u201cmodern forms of distraction.\u201d",
    anchor: { rating: "Weak", note: "The poem has episodes of temptation and delay (Lotus-Eaters, Book 9; Sirens, Book 12; Circe and Calypso), but no concept of addiction." },
    uptake: { rating: "Weak", note: "ThinkScope has not checked independent modern uptake for this specific framing." },
    resistance: { rating: "Weak", note: "Applying a modern clinical category to ancient episodes is anachronistic unless clearly framed as metaphor. (ThinkScope inference.)" } },
];

/* ---------- 5. Ancient element -> modern question matrix ---------- */
export interface Block { kind: BadgeKind; text: string }
export interface MatrixItem { id: string; ancient: string; modern: string; text: Block; interp: Block; limit: Block; ai: Block }
export const MATRIX: MatrixItem[] = [
  { id: "nostos", ancient: "Nostos / homecoming", modern: "What does \u201chome\u201d mean after major change?",
    text: { kind: "text", text: "Odysseus is away for about twenty years, ten at Troy and ten returning, and the poem's second half is about re-entering his own household." },
    interp: { kind: "interp", text: "Readers connect it to veteran reintegration, migration and personal transformation. Shay's Odysseus in America is a documented example for veterans; the others are less documented." },
    limit: { kind: "unc", text: "Ancient nostos means return to household and status. Modern exile or migration is a different experience." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses." } },
  { id: "disguise", ancient: "Disguise", modern: "Who are we when our identity is hidden?",
    text: { kind: "text", text: "Athena makes Odysseus look like an old beggar (Book 13), and he uses the disguise to test who in his household is loyal." },
    interp: { kind: "interp", text: "A common reading is that disguise lets the poem ask what remains of a person when status and appearance are removed." },
    limit: { kind: "unc", text: "Modern ideas of private, individual identity are not the poem's framework. Digital identity is a much looser parallel." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses under \u201cidentity & recognition.\u201d Digital identity is a distinctive emphasis in one analysis (Gemini)." } },
  { id: "recognition", ancient: "Recognition", modern: "What makes someone truly known?",
    text: { kind: "text", text: "Argos knows Odysseus at once (Book 17), Eurycleia knows his scar (Book 19), and Penelope tests him with the bed (Book 23)." },
    interp: { kind: "interp", text: "Auerbach's essay on the scar shows recognition has long been a critical focus. Asking what makes someone truly known extends that into modern relationships." },
    limit: { kind: "unc", text: "In the poem, recognition runs through tokens and secrets. Treating it as a general question about intimacy is the reader's step." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses (Claude names it as \u201crecognition/disguise\u201d)." } },
  { id: "xenia", ancient: "Xenia / hospitality", modern: "What do we owe strangers?",
    text: { kind: "text", text: "Hosts are judged by how they treat guests and beggars. Polyphemus fails the test; the Phaeacians and Eumaeus pass it; the suitors abuse it." },
    interp: { kind: "interp", text: "Scholarship treats guest-friendship as a core institution of the poem's world. Modern readings link it to refugees and migrants." },
    limit: { kind: "unc", text: "Xenia was reciprocal, status-bound and backed by Zeus. The modern refugee link is an interpretation, not an equivalence." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses." } },
  { id: "war", ancient: "War", modern: "What happens after the war ends?",
    text: { kind: "text", text: "The poem begins after Troy. Odysseus weeps at the singer's tale of the war (Book 8) and meets dead comrades in the Underworld (Book 11)." },
    interp: { kind: "interp", text: "Some readers treat the voyage as an aftermath story, for example in Shay's reading alongside combat trauma." },
    limit: { kind: "unc", text: "Modern psychological categories such as trauma and reintegration are not ancient concepts. The reading is disputed." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses; Gemini links it most directly to veteran reintegration." } },
  { id: "family", ancient: "Family", modern: "Can relationships survive prolonged absence?",
    text: { kind: "text", text: "Penelope delays the suitors by weaving and unweaving (Books 2 and 19). Telemachus grows from a passive son into an active one." },
    interp: { kind: "interp", text: "Readers see endurance and loyalty under long separation, which they connect to modern families divided by work, war or migration." },
    limit: { kind: "unc", text: "The household is patriarchal and economic, not a modern family of equals." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses." } },
  { id: "mortality", ancient: "Mortality", modern: "What makes a finite life meaningful?",
    text: { kind: "text", text: "Odysseus refuses Calypso's offer of immortality (Book 5) and speaks with the dead in Book 11." },
    interp: { kind: "interp", text: "A common reading is that he chooses a mortal life with Penelope over deathless comfort. This page cites no specific scholarship for the modern extension." },
    limit: { kind: "unc", text: "Ancient views of death and fame differ from modern ones. This theme was a distinctive emphasis in one analysis only." },
    ai: { kind: "aiinf", text: "Distinctive emphasis in one analysis (Claude)." } },
  { id: "revenge", ancient: "Revenge", modern: "When does justice become violence?",
    text: { kind: "text", text: "In Book 22 Odysseus and Telemachus kill the suitors, and household women judged disloyal are hanged." },
    interp: { kind: "interp", text: "Readers debate whether the slaughter is justice, excess, or both. Claude names moral ambiguity as a theme." },
    limit: { kind: "unc", text: "The poem's own stance is debated, and ancient ideas of justice and honour are not modern legal ideas." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by two analyses (Gemini and Claude)." } },
  { id: "story", ancient: "Storytelling", modern: "Why do societies keep retelling old stories?",
    text: { kind: "text", text: "Odysseus narrates his adventures to the Phaeacians (Books 9\u201312), and singers such as Demodocus perform within the poem." },
    interp: { kind: "interp", text: "The poem is about stories as well as journeys, which fits the long history of translation and adaptation. Emily Wilson's 2017 translation and Madeline Miller's Circe are recent examples." },
    limit: { kind: "unc", text: "Persistence of retelling does not show that audiences find the poem personally relevant." },
    ai: { kind: "aiinf", text: "Coded by ThinkScope as emphasized by all three analyses." } },
];

/* ---------- 6. Ancient != Modern ---------- */
export const ANCIENT = ["Aristocratic household economy", "Inherited status", "Slavery", "Patriarchal social structures", "Divine intervention", "Honour and reputation", "Warrior culture", "Ancient concepts of hospitality"];
export const MODERN = ["Individual identity", "Democratic institutions", "Modern migration", "Professional life", "Digital identity", "Modern ideas of equality", "Modern legal systems", "Contemporary ideas of psychology"];

/* ---------- 7. 2026 test ---------- */
export const FIGURES: { when: string; value: string; text: string; src: Src }[] = [
  { when: "July 2026", value: "$264.1M", text: "Worldwide opening weekend, reported by Variety.", src: { label: "Variety India", href: "https://varietyindia.com/box-office-the-odyssey-stuns-with-124-million-opening-weekend-third-biggest-debut-of-the-year/" } },
  { when: "August 2026", value: "$1B+", text: "Crossed $1 billion worldwide, reported by Variety.", src: { label: "TBS News (citing Variety)", href: "https://www.tbsnews.net/splash/nolans-odyssey-shows-staying-power-north-america-box-office-1498901" } },
  { when: "September 2026", value: "\u2248$1.68B", text: "Variety reported about $1.68 billion worldwide and called it Universal's highest-grossing film.", src: { label: "Variety (AU)", href: "https://au.variety.com/?p=40225" } },
];
export const BUDGET: { text: string; src: Src } = { text: "A production budget of about $250 million, excluding marketing, was reported by PA Media/dpa.", src: { label: "Malay Mail (PA/dpa)", href: "https://www.malaymail.com/news/showbiz/2026/09/13/the-odyssey-overtakes-jurassic-world-as-universals-highest-grossing-film-of-all-time/235026" } };
export const DATA_SHOWS = ["Major contemporary audience attention to the film", "Strong commercial performance", "Renewed visibility for a very old story", "Substantial investment in a Homeric adaptation"];
export const DATA_NOT = ["That audiences read Homer", "That audiences finished the poem", "That audiences understood ancient Greek context", "That Nolan's film succeeded because of the poem's themes", "That the poem will remain relevant after the film cycle ends"];

/* ---------- 8. Film vs poem ---------- */
export interface FilmRow { id: string; label: string; poem: string; film: string; changes: string; remains: string; filmChecked: boolean }
export const FILM_ROWS: FilmRow[] = [
  { id: "home", label: "Home", filmChecked: true,
    poem: "Odysseus is kept from Ithaca for years, reaches it in Book 13, and the poem ends with his household restored.",
    film: "Press accounts report that he goes into self-imposed exile and sails west with Penelope to honour the men who did not return, while Telemachus takes the throne.",
    changes: "The return no longer ends in rule and restored order.", remains: "The long way back is still the spine of the story." },
  { id: "identity", label: "Identity", filmChecked: false,
    poem: "Athena disguises Odysseus as a beggar (Book 13), and the scar identifies him (Book 19). He is also the trickster who calls himself \u201cNobody\u201d (Book 9).",
    film: "One press account reports that the film almost entirely removes Odysseus the trickster, and another that Polyphemus loses the \u201cNobody\u201d trick. ThinkScope has not verified how the film handles disguise.",
    changes: "The trickster side is reportedly reduced.", remains: "Not verified." },
  { id: "hospitality", label: "Hospitality", filmChecked: false,
    poem: "Xenia is tested in Polyphemus' cave, among the Phaeacians, in Eumaeus' hut and in a household overrun by suitors.",
    film: "ThinkScope has not verified how the film treats hospitality. One report notes an added anxiety about \u201cpeople from the sea\u201d invading territories, which does not overtly appear in Homer.",
    changes: "Reportedly adds a contemporary-sounding fear of outsiders.", remains: "Not verified." },
  { id: "war", label: "War", filmChecked: true,
    poem: "Troy lies behind the poem and is recalled through songs and Odysseus' own accounts (Books 8 and 11).",
    film: "One report says the film opens with the fall of Troy shown on screen, which establishes the trauma his journey carries.",
    changes: "War is shown, not only remembered.", remains: "The war's aftermath still shapes the journey." },
  { id: "family", label: "Family", filmChecked: true,
    poem: "Penelope weaves and unweaves to delay the suitors, tests Odysseus with the bed (Book 23), and Odysseus meets his father Laertes.",
    film: "Reports say Penelope's bed test is replaced by a brooch, Laertes is cut, and Penelope often rebukes Telemachus.",
    changes: "Several family scenes and roles are reworked.", remains: "Penelope, Telemachus and the household remain at the centre." },
  { id: "violence", label: "Violence", filmChecked: true,
    poem: "In Book 22 the suitors are killed and household women judged disloyal are hanged.",
    film: "One report says the film softens the final act and reduces the maids' punishment to a single handmaid, Melantho, whose fate Penelope decides.",
    changes: "The poem's most brutal moments are reportedly softened.", remains: "The reckoning with the suitors still forms the climax, according to press accounts." },
  { id: "mortality", label: "Mortality", filmChecked: false,
    poem: "Odysseus declines Calypso's offer of immortality (Book 5) and meets the dead in Book 11.",
    film: "Reports say Calypso is recast as a sympathetic figure who gives him lotus flowers to ease trauma. ThinkScope has not verified whether the immortality choice appears.",
    changes: "Calypso's role is reportedly recast.", remains: "Not verified." },
  { id: "story", label: "Storytelling", filmChecked: true,
    poem: "Odysseus tells his adventures to the Phaeacians (Books 9\u201312).",
    film: "Reports say he recounts them to Calypso on her island instead.",
    changes: "The listener changes.", remains: "The voyage is still told in retrospect." },
];
export const FILM_SOURCES: Src[] = [
  { label: "SuperHeroHype", href: "https://www.superherohype.com/news/679436-the-odyssey-changes-christopher-nolan-movie-homer-book" },
  { label: "JustWatch guide", href: "https://guides.justwatch.com/uk/how-accurate-christopher-nolan-the-odyssey" },
  { label: "Variety India", href: "https://varietyindia.com/the-odyssey-all-the-ways-christopher-nolans-movie-is-different-from-the-book/" },
  { label: "Tribune", href: "https://tribune.com.pk/story/2619163/every-major-way-christopher-nolan-changed-homers-the-odyssey-for-the-big-screen" },
];

/* ---------- 9. Relevance map ---------- */
export interface MapNode { id: string; label: string; text: string; modern: string; strength: string; ai: string; counter: string }
export const MAP_NODES: MapNode[] = [
  { id: "home", label: "HOME", text: "Odysseus is kept from Ithaca for years and the second half of the poem is about regaining it (Books 1, 5, 13\u201323).", modern: "Read as a question about what home means after major change, with links to veteran reintegration, migration and exile.", strength: "Strong textual foundation; moderate modern equivalence.", ai: "All three analyses.", counter: "Ancient nostos is a return to household and status. Modern displacement is a different experience." },
  { id: "identity", label: "IDENTITY", text: "Disguise, false names and recognition recur: the beggar disguise, the scar, the bed (Books 13, 19, 23).", modern: "Read as a question about who we are when others cannot see us. Digital identity is a looser parallel.", strength: "Strong textual foundation; moderate modern equivalence.", ai: "All three analyses (Claude: recognition/disguise).", counter: "The poem has no modern concept of private selfhood. The online-identity link comes from the reader." },
  { id: "family", label: "FAMILY", text: "Penelope's weaving delay, Telemachus' growth and Laertes' reunion centre the household (Books 2, 19, 24).", modern: "Read as a question about whether relationships survive long absence.", strength: "Strong textual foundation; moderate modern equivalence.", ai: "Coded as all three analyses.", counter: "The household is patriarchal and economic, and includes enslaved people." },
  { id: "war", label: "WAR", text: "Troy is the backstory, recalled in songs and in the Underworld (Books 8, 11).", modern: "Read as an aftermath story, for example in Shay's work on combat trauma.", strength: "Moderate textual presence as memory; modern equivalence contested.", ai: "Coded as all three analyses; Gemini links it to veteran reintegration.", counter: "Modern trauma categories are not ancient ones, and the reading is disputed." },
  { id: "strangers", label: "STRANGERS", text: "Xenia is tested repeatedly: Polyphemus, the Phaeacians, Eumaeus and the suitors (Books 6\u201314, 17\u201320).", modern: "Read as a question about what we owe strangers.", strength: "Strong textual foundation; moderate modern equivalence.", ai: "All three analyses (hospitality).", counter: "Xenia was reciprocal and status-bound, so the refugee parallel is an interpretation." },
  { id: "mortality", label: "MORTALITY", text: "Odysseus refuses Calypso's offer of immortality (Book 5) and meets the dead (Book 11).", modern: "Read as a question about what makes a finite life meaningful.", strength: "Strong textual foundation; modern equivalence is ThinkScope's conceptual judgement.", ai: "Distinctive emphasis in one analysis (Claude).", counter: "Only one analysis stresses it, and this page cites no specific scholarship for the modern extension." },
  { id: "choice", label: "CHOICE", text: "Zeus complains in Book 1 that mortals blame the gods for troubles they bring on themselves, while gods also steer events.", modern: "Read as a tension between fate and agency.", strength: "Mixed: explicit in the text, but divine intervention is hard to map onto modern agency.", ai: "Coded as all three analyses (fate and choice).", counter: "Divine intervention does not map neatly onto modern ideas of agency." },
  { id: "revenge", label: "REVENGE", text: "Book 22 ends with the suitors killed and household women hanged.", modern: "Read as a question about when justice becomes violence.", strength: "Strong textual foundation; modern reading is contested.", ai: "Two analyses (Gemini and Claude).", counter: "The poem's own stance is debated, and honour-based vengeance is not modern justice." },
  { id: "story", label: "STORYTELLING", text: "Odysseus narrates Books 9\u201312 to the Phaeacians; singers perform within the poem.", modern: "Read as a question about why societies keep retelling old stories.", strength: "Strong textual foundation; retelling is documented, personal relevance is not measured here.", ai: "Coded as all three analyses.", counter: "Retelling shows persistence, which is not the same as personal relevance." },
];

/* ---------- 10. Timeless or renewable ---------- */
export const CHOICES = [
  { id: "A", label: "Universal human problems", yours: "You lean toward the view that the poem keeps asking questions that people everywhere meet, such as what home is and what we owe strangers. The counterargument section below tests how far \u201cuniversal\u201d can stretch.",
    ai: { gemini: "Treats many themes as mappable onto modern experience, but cautions that the links are interpretations.", chatgpt: "Closest to this in spirit, but narrower: the circumstances are not universal, the questions can be transferable.", claude: "Questions whether \u201ctimeless\u201d fits and prefers \u201crenewable.\u201d" } },
  { id: "B", label: "Its adaptability", yours: "You lean toward the view that the story survives because it can be reshaped for new questions without breaking.",
    ai: { gemini: "Closest to this: its emphasis is modern parallels and adaptability.", chatgpt: "Describes adaptable human problems, while noting that adaptation alone does not prove personal relevance.", claude: "Frames the poem as renewable through retelling, and asks for evidence behind each connection." } },
  { id: "C", label: "Cultural institutions keep it alive", yours: "You lean toward the view that education, publishing and institutional prestige do much of the work. This is a hypothesis, and ThinkScope has no data on how much.",
    ai: { gemini: "Does not foreground institutions in its main emphasis.", chatgpt: "Cautions that continued cultural attention does not prove audiences find it personally relevant.", claude: "Cautions that attention to adaptations does not prove reading or long-term relevance." } },
  { id: "D", label: "Modern creators keep reinventing it", yours: "You lean toward the view that each generation of translators, writers and filmmakers renews it. This is close to the \u201crenewable\u201d idea.",
    ai: { gemini: "Points to modern experiences the story is mapped onto, which creators and readers supply.", chatgpt: "Names storytelling among its themes and notes that adaptations show attention, not necessarily personal relevance.", claude: "Closest to this: names retelling as a theme and calls the poem renewable." } },
];
export const AI_LINES = { gemini: "Gemini emphasizes\u2026", chatgpt: "ChatGPT emphasizes\u2026", claude: "Claude emphasizes\u2026" } as const;

/* ---------- 11. Counterarguments ---------- */
export const COUNTERS: { text: string; kind: LabelKind; more: string }[] = [
  { text: "Ancient social structures were radically different.", kind: "fact", more: "The poem's world is an aristocratic household economy built on inherited status, gift exchange and honour." },
  { text: "The poem contains slavery and patriarchal structures.", kind: "fact", more: "Eumaeus and Eurycleia are enslaved, the twelve maids are hanged in Book 22, and in Book 1 Telemachus tells Penelope that speech is men's business." },
  { text: "Violence is central to the narrative.", kind: "fact", more: "The poem climaxes in the killing of the suitors, and the hero blinds Polyphemus and loses his crew along the way." },
  { text: "Odysseus is morally complicated.", kind: "supported", more: "He taunts Polyphemus and reveals his name, which brings Poseidon's anger (Book 9). Claude names moral ambiguity as a theme." },
  { text: "Divine intervention does not map neatly onto modern ideas of agency.", kind: "inference", more: "Athena steers events constantly, while Zeus says mortals bring troubles on themselves. Modern readers have to choose how to read that tension." },
  { text: "\u201cUniversal human experience\u201d can become too vague to be useful.", kind: "inference", more: "If a theme can mean anything, it can be proved by anything. That is why the evidence test asks for a textual anchor and independent modern uptake." },
  { text: "Cultural persistence may partly reflect education, publishing, institutional prestige and repeated adaptation.", kind: "uncertain", more: "This is a plausible hypothesis, not a finding. ThinkScope has no data on how much each factor contributes." },
];
export const COUNTER_Q = { q: "If the world is not universal, does that make the questions less transferable?", opts: [
  { id: "less", label: "Yes, less transferable", note: "You treat the differences as a real limit. The evidence test is built for this view: it asks whether a connection survives them." },
  { id: "same", label: "No, the questions still travel", note: "You treat the questions as separable from the institutions, which is close to ChatGPT's transferable-question framing. The risk is vagueness." },
  { id: "depends", label: "It depends on the question", note: "You judge each question on its evidence. Hospitality may travel differently from divine fate, for example." },
] };

/* ---------- 12. FAQ ---------- */
export const FAQ: { q: string; a: string }[] = [
  { q: "Why is The Odyssey still relevant today?", a: "That is a matter of interpretation. Readers and adaptors keep returning to its questions about home, identity, hospitality and mortality, and three AI analyses repeatedly emphasized homecoming, identity and hospitality. Continued attention does not by itself show that any individual finds it personally relevant." },
  { q: "What themes in The Odyssey connect with modern audiences?", a: "Commonly cited themes are homecoming, identity and recognition, family, hospitality, temptation, storytelling and fate versus choice. Modern parallels such as migration, veteran reintegration or digital identity are interpretations, not features of the poem." },
  { q: "Is The Odyssey actually timeless?", a: "ThinkScope does not decide this. One AI analysis suggested \u201crenewable\u201d may fit better: the story persists because each generation translates and retells it around new questions." },
  { q: "What does \u201cnostos\u201d mean?", a: "Nostos is the Greek word for homecoming or return, and it is a central idea in the poem and in the wider tradition of stories about returning from Troy." },
  { q: "How is The Odyssey different from modern stories about homecoming?", a: "The poem's return is to a household, status and kin in an aristocratic world with gods who intervene. Modern stories usually concern individual identity, migration or psychology, so the overlap is in the questions more than the institutions." },
  { q: "Why does The Odyssey keep being adapted?", a: "There is no single measured cause. Likely factors include its episodic structure, its place in education and publishing, and its open questions, though ThinkScope has no data on how much each contributes." },
  { q: "Does the 2026 film prove The Odyssey is still relevant?", a: "No. Variety reported about $1.68 billion worldwide by September 2026, which shows major attention to the film. It does not show that audiences read, finished or understood the poem, or that the film succeeded because of its themes." },
  { q: "What is the difference between The Odyssey's ancient values and modern interpretations?", a: "Ancient values in the poem include honour, status, xenia and obedience to the gods. Modern interpretations apply later ideas such as individual identity, equality and psychology to those episodes, so they should be read as interpretations." },
];

/* ---------- 13. Sources ---------- */
export const SOURCES: { group: string; items: Src[] }[] = [
  { group: "The poem", items: [
    { label: "Homer, Odyssey (Perseus Digital Library)", href: "https://www.perseus.tufts.edu/hopper/text?doc=Hom.+Od." },
    { label: "Britannica: Odyssey", href: "https://www.britannica.com/topic/Odyssey-epic-by-Homer" },
    { label: "Nostos", href: "https://en.wikipedia.org/wiki/Nostos" },
    { label: "Xenia (Greek)", href: "https://en.wikipedia.org/wiki/Xenia_(Greek)" } ] },
  { group: "Modern uptake", items: [
    { label: "Jonathan Shay, Odysseus in America (2002)", href: "https://en.wikipedia.org/wiki/Jonathan_Shay" },
    { label: "Auerbach, Mimesis (1946)", href: "https://en.wikipedia.org/wiki/Mimesis:_The_Representation_of_Reality_in_Western_Literature" } ] },
  { group: "The 2026 film", items: [...FIGURES.map((f) => f.src), BUDGET.src, ...FILM_SOURCES] },
];
